env:
  - TEST_SUITE=testinstall
  - TEST_SUITE=testall
  - TEST_SUITE=bugfix
language: c
compiler:
  - gcc
  - clang
# Change this to your needs
script:
  - ./configure
  - make 
  - mkdir pkg
  - cd pkg
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/GAPDoc-1.5.1.tar.gz
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/autpgrp-1.5.tar.gz
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/atlasrep1r5p0.tar.gz
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/ctbllib-1r2p2.tar.gz
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/grpconst-2.3.tar.gz
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/irredsol-1r2n4.tar.gz
  - wget ftp://ftp.gap-system.org/pub/gap/gap47/tar.gz/packages/tomlib1r2p4.tar.gz 
  - tar xvzf GAPDoc-1.5.1.tar.gz
  - tar xvzf autpgrp-1.5.tar.gz
  - tar xvzf atlasrep1r5p0.tar.gz
  - tar xvzf ctbllib-1r2p2.tar.gz
  - tar xvzf grpconst-2.3.tar.gz
  - tar xvzf irredsol-1r2n4.tar.gz
  - tar xvzf tomlib1r2p4.tar.gz
  - cd ..
  - if [[ "$TEST_SUITE" == "testinstall" ]]; then echo "Read(\"tst/testinstall.g\"); quit;" | sh bin/gap.sh ; fi
  - if [[ "$TEST_SUITE" == "testall" ]]; then echo "Read(\"tst/testall.g\"); quit;" | sh bin/gap.sh ; fi
  - if [[ "$TEST_SUITE" == "bugfix" ]]; then echo "Test(\"tst/bugfix.tst\"); quit;" | sh bin/gap.sh -q ; fi
