# set clone depth
clone_depth: 5                  # clone entire repository history if not defined

install:
  - 'C:\cygwin\setup-x86.exe -qnNdO -R C:/cygwin -s http://cygwin.mirror.constant.com -l C:/cygwin/var/cache/setup -P autoconf -P automake -P bison -P libgmp-devel -P gcc-core -P gcc-g++ -P mingw-runtime -P mingw-binutils -P mingw-gcc-core -P mingw-gcc-g++ -P mingw-pthreads -P mingw-w32api -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config -P git -P wget -P curl'

# scripts that run after cloning repository
build_script:
  - 'C:/cygwin/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER ; ./configure --with-gmp=system && make cygwin && make bootstrap-pkg-full"'

test_script:
  - 'C:/cygwin/bin/bash -lc "cd $APPVEYOR_BUILD_FOLDER ; make testinstall"'
